### ISSUE TITLE
Adding host is messy

### ISSUE THREAD

**Issue by aaronmee** [OneLiberty/moonlight-chrome-tizen#8] opened 2023-12-15 19:34 UTC
First of all, thanks for your changes :)

But one thing I noticed when I want to connect to my pc is that when I choose a number from this dropdown, 192, for example, and then switch to the right, the number increases by one. So I have to select one number lower than intended to equalize the effect. You have an idea what could be causing this?

Another thing I noticed is that I get errors most of the time when I want to pair my TV with my PC. I click on connect, remember the pin and enter it on my pc upstairs, but the tv just tells me that pairing failed. This is probably not related to this repo but I never experienced that before. Maybe I have to be faster. Gonna try that xD

Keep up the good work

**Comment by sieskei** [comment] 2023-12-15 21:19
Hello,
I can confirm for all mentioned bugs.
BTW about pairing - try to add same pin code again when you get error.

**Comment by OneLiberty** [comment] 2023-12-16 09:07
@aaronmee 
1. No i have no idea why it's doing this. I highly suggest using a gamepad for the IP. For some reason using the gamepad doesn't increment/decrement when changing field. 
If anyone has an idea, i'll take it, I spent almost a week trying things to fix this without success... 

2. Unfortunatly, i have no error pairing on my side so i can't really fix this, If you could check if there are any error on the debug logs of the apps, this would be very useful. 

EDIT: I thing i've been able to replicate the issue. This might have to do with the SSL public key and PPK. (Got this error on log console : SSL public key does not match pinned public key) 
Did you try, in the past to pair to the PC ? @aaronmee @sieskei Could you try to "Unpair All clients" in sunshine settings (in the "troubleshooting" section) ?

**Comment by AlexPresso** [comment] 2023-12-22 02:30
> If anyone has an idea, i'll take it

Regarding 1. I was also spending time trying to fix this, there could be something with the `focus`/`unfocus` event, but I can't find it yet... Something strange is that when trying to check the "manual input" checkbox, it doesn't keeps its state and get instantly unchecked. So it could also be something messing with the latest Tizen SDK

**Comment by OneLiberty** [comment] 2023-12-22 09:20
@AlexPresso 

Thanks for taking the time to look at it

What's strange is that gamepad (at least on my end) doesn't have any of those issues. 
So I think this has to do with the either remote handler, or Samsung implementation of it. 

Seems like there are some buttons that are always registered (left right up down and enter). 
Also two different enter button exist key_enter and key_remote_enter I don't know the differences. 

For the toggle, it's not that it doesn't keep the state. I think it's because two input are triggered (when pressed and released), this causes issue with some other element on the page too. 
We should probably log the input to the console to see what's happening exactly in the app. 

For now, I can only suggest using a controller instead of the remote.

**Comment by aaronmee** [comment] 2023-12-27 22:51
Thank you for your responses!

@AlexPresso entering the pin code twice is working, thank you for that.
Regarding 2., I'll just use my BT keyboard :)

**Comment by OneLiberty** [comment] 2024-01-09 15:46
Accidentally closed issue. 
Waiting for feedback before closing

Seems like increment is fixed when using remote. 
Still looking for the pairing issue

**Comment by aaronmee** [comment] 2024-01-15 21:44
Thank you, I'll test it when I find some time

**Closed as completed** 2024-02-19 20:34 UTC
